name: Cypress Tests

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js (20.5.1)
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.1

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes com Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # ou electron/firefox
